#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -t 2 ]; then
  exec >/dev/tty 2>&1
fi

pnpm test
# Disable concurent to run `check-types` after ESLint in lint-staged
pnpm lint-staged --concurrent false
